# Generated by Django 4.1.7 on 2023-03-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_rename_product_id_orderdetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_id',
        ),
    ]
